EXTRA_DIST         = lib.sh sanity.sh basic.sh iface.sh conf.sh osrel.sh ipv6.sh srcaddr.sh wildcard.sh ifall.sh netlink.sh hrstorage.sh hrsystem.sh cpuload.sh trap.sh reload.sh droppriv.sh bulk.sh readonly.sh custom.sh stats.sh sysor.sh
CLEANFILES         = *~ *.trs *.log

TEST_EXTENSIONS    = .sh
TESTS_ENVIRONMENT  = unshare -mrun --map-auto

TESTS              = sanity.sh
TESTS             += basic.sh
TESTS             += iface.sh
TESTS             += conf.sh
TESTS             += osrel.sh
TESTS             += ipv6.sh
TESTS             += srcaddr.sh
TESTS             += wildcard.sh
TESTS             += ifall.sh
TESTS             += netlink.sh
TESTS             += hrstorage.sh
TESTS             += hrsystem.sh
TESTS             += cpuload.sh
TESTS             += trap.sh
TESTS             += reload.sh
TESTS             += droppriv.sh
TESTS             += bulk.sh
TESTS             += readonly.sh
TESTS             += custom.sh
TESTS             += stats.sh
TESTS             += sysor.sh
