EXTRA_DIST         = lib.sh sanity.sh basic.sh iface.sh conf.sh osrel.sh ipv6.sh srcaddr.sh
CLEANFILES         = *~ *.trs *.log

TEST_EXTENSIONS    = .sh
TESTS_ENVIRONMENT  = unshare -mrun --map-auto

TESTS              = sanity.sh
TESTS             += basic.sh
TESTS             += iface.sh
TESTS             += conf.sh
TESTS             += osrel.sh
TESTS             += ipv6.sh
TESTS             += srcaddr.sh
