name: Bob the Builder

# Run on all branches, including all pull requests, except the 'dev'
# branch since that's where we run Coverity Scan (limited tokens/day)
on:
  push:
    branches:
      - '**'
      - '!dev'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Verify we can build on latest Ubuntu with both gcc and clang,
    # then run the namespace-based smoke tests.
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false
    env:
      MAKEFLAGS: -j3
      CC: ${{ matrix.compiler }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install pkg-config libconfuse-dev libsystemd-dev ethtool snmp snmptrapd tree tshark tcpdump
      - uses: actions/checkout@v6
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --prefix=
      - name: Build
        run: |
          make V=1
      - name: Install
        run: |
          DESTDIR=~/tmp make install-strip
          tree ~/tmp
          ldd ~/tmp/sbin/mini-snmpd
          size ~/tmp/sbin/mini-snmpd
          ~/tmp/sbin/mini-snmpd -h
      - name: Enable unprivileged userns (unshare)
        run: |
          sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
      - name: Run smoke tests
        run: |
          make check || (cat test/test-suite.log; false)
      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: mini-snmpd-test-${{ matrix.compiler }}
          path: test/*
